ALTER TABLE usuarios DROP COLUMN IF EXISTS rg;
ALTER TABLE usuarios DROP COLUMN IF EXISTS nacionalidade;
ALTER TABLE usuarios DROP COLUMN IF EXISTS estado_civil;
ALTER TABLE usuarios DROP COLUMN IF EXISTS cep;
ALTER TABLE usuarios DROP COLUMN IF EXISTS logradouro;
ALTER TABLE usuarios DROP COLUMN IF EXISTS numero;
ALTER TABLE usuarios DROP COLUMN IF EXISTS complemento;
ALTER TABLE usuarios DROP COLUMN IF EXISTS bairro;
